### ISSUE TITLE
Uploaded image not found (error 404)

### ISSUE THREAD

**Issue by mattes3** [parcelvoy/platform#381]
When I upload an image inside the email template editor, it lands in my `./data/uploads` directory correctly. However, when I want to preview the email, the image is not found. The server returns HTTP 404 (not found).

In my `.env` file, next to the docker compose file, I have this setting:

```
STORAGE_DRIVER=local
STORAGE_BASE_URL=https://my-domain.com/uploads
```

In the docker-compose file, the volume declaration looks like this:

```yaml
volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql

  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis

  uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/uploads
```

Upload works fine, the image is in the correct directory!

These are the permissions of the directory:

```bash
drwxr-xr-x 2             1000             1000 4096 Mar 10 15:38 uploads
```
What needs to be done here?
